# Generated by Django 5.1 on 2024-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='interaction-files/'),
        ),
    ]
