# Generated by Django 5.1 on 2024-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_interaction_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='avalicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
