# Generated by Django 5.1 on 2024-09-15 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_interaction_avalicao_alter_interaction_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='avalicao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
