# Generated by Django 5.1 on 2024-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_alter_interaction_avalicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='avalicao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
