# Generated by Django 5.1 on 2024-09-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_alter_interaction_avalicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='avalicao',
            new_name='avaliacao',
        ),
    ]
