# Generated by Django 5.1 on 2024-09-17 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_rename_avalicao_interaction_avaliacao'),
        ('pixel', '0004_pixel_created_at_pixel_deleted_at_pixel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='pixelPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixel.pixel'),
        ),
    ]
