# Generated by Django 5.1 on 2024-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_pixel_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
